newProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('taskManager/', include("taskManager.urls")),
    path('admin/', admin.site.urls),
]

taskManager/urls.py
from taskManager import views
from django.urls import  path

app_name = "taskManager"

urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.addTask, name="add")
]

taskManager/models.py
from django.db import models

# Create your models here.

taskManager/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse


class creatNewForm(forms.Form):
    task = forms.CharField(label="Add new Task")

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []   
    return render(request, "taskmanager/index.html",{
        "tasks" : request.session["tasks"]
    })

def addTask(request):
    if request.method == "POST":
        form = creatNewForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("taskManager:index"))
        else :
            return render(request, "taskManager/addTask.html", {
                "form" : form
            })


    return render(request, "taskManager/addTask.html",{
        "form" : creatNewForm()
    })

newProject/templates/taskManager/addTask.html
{%extends "taskManager/layout.html"%}
   
{%block body%}
    <h1>Add Task</h1>
    <form action="{% url 'taskManager:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button>Submit</button>
     <a href="{% url 'taskManager:index'%}">Tasks Page </a>
    </form>
{%endblock%}

newProject/templates/taskManager/index.html
{%extends "taskManager/layout.html"%}


{% block body %}
    <h1>My TaskManager</h1>

    <ul>
      {% for i in tasks %}
      <li >{{ i }}</li>
      {% empty %}
      <li> No Task for now </li>
      {% endfor %}
    </ul>
    <a href="{%url 'taskManager:add'%}">Add Task</a>
{%endblock%}

newProject/templates/taskManager/layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Task</title>
    <link rel="stylesheet" href="{% static 'taskManager/style.css'%}">
</head>
<body>
    {%block body%}

    {%endblock%}
</body>
</html>